config/routes.rb
Devmail::Engine.routes.draw do
  resources :messages do
    get :send_test, on: :collection
    get :html_part, on: :member
  end
  root to: 'messages#index'
end

Rails.application.routes.draw do
  mount Devmail::Engine => "/devmail"
end

app/models/devmail/dev_mail.rb
module Devmail
  class DevMail
    include Mongoid::Document
    include Mongoid::Timestamps

    field :from, :type => Array
    field :to, :type => Array
    field :cc, :type => Array
    field :bcc, :type => Array
    field :header
    field :sender
    field :subject
    field :reply_to, :type => Array
    field :text_part
    field :html_part
    field :multipart, :type => Boolean
    field :content_transfer_encoding

    field :serialized_mail

    def mail
      Mail::Message.from_yaml(self.serialized_mail)
    end

    def mail=(m)
      self.serialized_mail = m.to_yaml
    end
  end
end

app/controllers/devmail/application_controller.rb
module Devmail
  class ApplicationController < ActionController::Base
  end
end

app/controllers/devmail/development_mails_controller.rb
module Devmail
  class DevelopmentMailsController < ApplicationController
    respond_to :html, :xml, :json

    layout "devmail/devmail"

    def index
      @mails = DevMail.all.desc(:created_at)

      respond_with @mails
    end

    def show
      @mail = DevMail.find(params[:id])

      respond_with @mail
    end

    def destroy
      @mail = DevMail.find(params[:id])
      @mail.destroy

      redirect_to development_mails_url
    end

    def clear
      DevMail.destroy_all
      redirect_to development_mails_url
    end

    def html_part
      @mail = DevMail.find(params[:id])
      render :text => @mail.html_part
    end
  end
end

app/controllers/devmail/messages_controller.rb
require_dependency "devmail/application_controller"

module Devmail
  class MessagesController < ApplicationController
    def index
      @messages = Devmail.messages
    end

    def show
      @message = Devmail.find_message(params[:id])
    end

    def html_part
      @message = Devmail.find_message(params[:id])
      render text: @message.html_part
    end

    def send_test
      Sample.test.deliver
      redirect_to action: :index
    end
  end
end

app/helpers/devmail/application_helper.rb
module Devmail
  module ApplicationHelper
  end
end

app/helpers/devmail/messages_helper.rb
module Devmail
  module MessagesHelper
  end
end

app/views/devmail/development_mails/index.html.erb
<h1>Development e-mails captured:</h1>

<table>
  <tr>
    <th>Sent at</th>
    <th>From</th>
    <th>To</th>
    <th>Subject</th>
    <th></th>
  </tr>
  <% for mail in @mails do -%>
    <tr>
      <td><%= mail.created_at.in_time_zone %></td>
      <td><%= mail.from.join(", ") %></td>
      <td><%= mail.to.join(", ") %></td>
      <td><%= mail.subject %></td>
      <td><%= link_to "Details", development_mail_path(mail) %>, 
        <%= link_to "Delete", development_mail_path(mail), :confirm => 'Are you sure?', :method => :delete %>
      </td>
    </tr>
  <% end -%>
</table>

<%= link_to "Clear", clear_development_mails_path,
  :confirm => "Are you sure? This will remove all stored emails." %>

app/views/devmail/development_mails/show.html.erb
<h1>Development email</h1>

<p><b>Sent at:</b> <%= @mail.created_at.in_time_zone %></p>
<p><b>From:</b> <%= @mail.from.join(", ") %></p>
<p><b>To:</b> <%= @mail.to.join(", ") %></p>
<p><b>Subject:</b> <%= @mail.subject %></p>
<% if @mail.multipart? -%>
  <p><b>Text part:</b><br />
    <%= @mail.text_part.gsub(/\n/, "<br />").html_safe %>
  </p>
  <p>
    <b><%= link_to "HTML part", html_part_development_mail(@mail) %></b>
  </p>
<% else -%>
  <p><b>Body:</b><br />
    <%= @mail.text_part.gsub(/\n/, "<br />").html_safe %>
  </p>
<% end -%>

<%= link_to "Back to list", development_mails_path %>
<%= link_to 'Delete', development_mail_path(@mail), :confirm => 'Are you sure?', :method => :delete %>

app/views/devmail/messages/index.html.erb
<div class="row">
  <div class="span12">
    <h1>Messages</h1>
    <ol>
    <% @messages.each_with_index do |message, index| %>
      <li><%= link_to message.summary, message_path(index) %></li>
    <% end %>
    </ol>
    <p><%= @messages.inspect %></p>
  </div>
</div>

app/views/devmail/messages/show.html.erb
<table class="table table-condensed">
  <tr>
    <th>To</th>
    <td><%= @message.to.join(", ") %></td>
  </tr>

  <tr>
    <th>CC</th>
    <td><%= @message.cc.join(", ") %></td>
  </tr>

  <tr>
    <th>BCC</th>
    <td><%= @message.bcc.join(", ") %></td>
  </tr>

  <tr>
    <th>From</th>
    <td><%= @message.from.join(", ") %></td>
  </tr>

  <tr>
    <th>Reply to</th>
    <td><%= @message.reply_to %></td>
  </tr>

  <tr>
    <th>Subject</th>
    <td><%= @message.subject %></td>
  </tr>

<!--   <tr>
    <th></th>
    <td><%= %></td>
  </tr>

  <tr>
    <th></th>
    <td><%= %></td>
  </tr>
 -->
</table>

<ul class="nav nav-tabs" id="format-select">
  <li class="active"><a href="#text" data-toggle="tab">Text</a></li>
  <% if @message.multipart %>
    <li><a href="#html" data-toggle="tab">HTML</a></li>
  <% end %>
</ul>

<div class="tab-content">
  <div class="tab-pane active" id="text">
    <pre><%= @message.text_part %></pre>
  </div>
  <% if @message.multipart %>
  <div class="tab-pane html-part-container" id="html">
    <iframe src="<%= html_part_message_path(params[:id]) %>">
  </div>
  <% end %>
</div>

app/views/devmail/sample/test.html.erb
<h1>Test email</h1>
<p>Sample paragraph</p>
<pre>pre block</pre>

app/views/devmail/sample/test.text.erb
Sample#test

<%= @greeting %>, find me in app/views/app/views/devmail/sample/test.text.erb

app/views/layouts/devmail/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Devmail</title>
  <%= stylesheet_link_tag    "devmail/application", :media => "all" %>
  <%= javascript_include_tag "devmail/application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-pills">
      <li class="<%= 'active' if action = 'index' %>">
        <%= link_to "Messages", messages_path %>
      </li>

      <li>
        <%= link_to "Send test message", send_test_messages_path %>
      </li>
    </ul>

    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/devmail/devmail.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Development Emails</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <style type="text/css">
    table td, table th {
      border: 1px solid #ccc;
      padding: 5px 10px;
    }
    table {
      border-collapse: collapse;
      border-spacing: 0;
    }
  </style>
</head>
<body>

<%= yield %>

</body>
</html>